apiVersion: v1
kind: Namespace
metadata:
  name: idp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: idp
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;

    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            location /adminer {
                proxy_pass http://adminer-service:8080;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: idp
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: idp
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer-container
        image: adminer:4.8.1
        ports:
        - name: adminer-port
          containerPort: 8080
      restartPolicy: Always
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: db-kubegres
  namespace: idp
spec:
  replicas: 3
  image: postgres:16.2
  database:
    size: 200Mi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: replicationUserPassword
    - name: POSTGRES_DB
      value: store
    - name: POSTGRES_USER
      value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: idp
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 30000
    targetPort: nginx-port
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: idp
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: adminer-port
---
