apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-deployment
  namespace: idp
spec:
  selector:
    matchLabels:
      app: io
  replicas: 3
  template:
    metadata:
      labels:
        app: io
      annotations:
        prometheus.io/metric_path: /actuator/prometheus
    spec:
      containers:
      - name: io
        image: 2001slavic/idp-proiect-io-service:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_USERNAME
          value: admin
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: superUserPassword
        - name: DATABASE_NAME
          value: store
        - name: IO_SERVICE_PORT
          value: "10000"
        - name: IO_SERVICE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: IO_SERVICE_DATASOURCE_URL
          value: jdbc:postgresql://db-kubegres:5432/${DATABASE_NAME}
        - name: IO_SERVICE_DATABASE
          value: postgresql
        ports:
        - name: io-port
          containerPort: 10000

      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-deployment
  namespace: idp
spec:
  selector:
    matchLabels:
      app: exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: exporter
      annotations:
        prometheus.io/metric_path: /metrics
    spec:
      containers:
      - name: exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: superUserPassword
        - name: DATA_SOURCE_NAME
          value: postgresql://admin:admin@db-kubegres:5432/postgres?sslmode=disable
        ports:
        - name: exporter-port
          containerPort: 9187

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: io-service
  namespace: idp
spec:
  type: ClusterIP
  selector:
    app: io
  ports:
    - port: 10000
      targetPort: io-port
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-service
  namespace: idp
spec:
  type: ClusterIP
  selector:
    app: exporter
  ports:
    - port: 9187
      targetPort: exporter-port
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-self
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: io
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: io
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-io
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: auth
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: io
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: io
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-auth
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: auth
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: auth
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-business-io
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: business-logic
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: io
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: io
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-business
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: business-logic
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: business-logic
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-db
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: db-kubegres
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: db-kubegres
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-io
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: io
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: io
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-portainer
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-io-prometheus
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: io
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: prometheus
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: prometheus
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-exporter-self
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: exporter
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: exporter
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: exporter
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-exporter-db
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: exporter
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: db-kubegres
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: db-kubegres
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-exporter
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: exporter
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: exporter
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-exporter-portainer
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: exporter
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-exporter-prometheus
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: exporter
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: prometheus
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: prometheus
  policyTypes:
  - Ingress
  - Egress
