apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: db-kubegres
  namespace: idp
spec:
  replicas: 3
  image: postgres:16.2
  database:
    size: 200Mi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: replicationUserPassword
    - name: POSTGRES_DB
      value: store
    - name: POSTGRES_USER
      value: admin
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-self
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: db-kubegres
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: db-kubegres
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-kubegres
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kubegres-system
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kubegres-system
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-adminer
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: adminer
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: adminer
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-adminer-db
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: adminer
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: db-kubegres
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: db-kubegres
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-portainer
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: portainer
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-prometheus
  namespace: idp
spec:
  podSelector:
    matchLabels:
      app: db-kubegres
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: prometheus
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: prometheus
  policyTypes:
  - Ingress
  - Egress
