name: Run Azure Login with System-assigned Managed Identity
on:
  push:
    branches:
      - main

jobs:
  login-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: idp-resource-group
          cluster-name: idp-cluster

      - uses: Azure/k8s-deploy@v1
        with:
          namespace: idp
          manifests: |
            _scripts/deploy-other.yaml
            _scripts/deploy-kubegres.yaml
            _scripts/deploy-io.yaml
    #   - name: Rollout
    #     run: kubectl rollout restart deploy -n idp
